### ISSUE TITLE
[Feature]: Support plain HTTP helm repo when running 'kdp install'

### ISSUE THREAD

**Issue by jason-ltc** [linktimecloud/kubernetes-data-platform#115]
### Implemented function

`kdp install --helm-repository oci://XXXX` supports pulling helm charts from plain HTTP scheme.

### What problem to solve?

Facts:
- when running `kdp install`, users may specify `--helm-repository oci://XXXX` to use private helm repo
- `helm pull` supports `--plain-http` option to pull helm charts from HTTP registry

Problem:
If users specify `kdp install --helm-repository oci://XXXX` from HTTP registry, pulling will fail in KDP fluxcd source controller:
<img width="1372" alt="image" src="https://github.com/linktimecloud/kubernetes-data-platform/assets/133080245/47713888-9ded-438c-a093-98e649a7a7c6">

### What version is expected to be completed?

A hotfix to 1.1 if possible.

**Comment by stdnt-xiao** [comment]
该问题已经在flucd的新版本里面解决
问题：
https://github.com/fluxcd/source-controller/issues/807
解决
https://github.com/fluxcd/source-controller/pull/1288
