### ISSUE TITLE
[Bug]: KDP平台安装时mysql组件初始化失败

### ISSUE THREAD

**Issue by stdnt-xiao** [linktimecloud/kubernetes-data-platform#139]
### KDP version

1.1.1

### What did you do?

Provide reference

### What did you see happen?

Kubernetes v1.22.12
Installing kdp, when the addon-mysql installation is reached, the MySQL installation will suddenly fail without any error prompts.

### What did you expect to see?
![image](https://github.com/linktimecloud/kubernetes-data-platform/assets/20313983/20f16263-1e77-43c0-856d-c18e13d0f94d)
<img width="1401" alt="image" src="https://github.com/linktimecloud/kubernetes-data-platform/assets/20313983/cf509bcc-03d4-4d4b-8079-bf66b560f89b">

**Comment by stdnt-xiao** [comment]
Through investigation, it was found that the version of Infra/mysql is 9.23.0. Upon checking the following official website, it was found that the minimum supported version of Kubernetes is Kubernetes 1.23+. 
After verification, adjusting the MySQL version to 9.12.3 can ensure successful installation.

The following is an official explanation:
https://artifacthub.io/packages/helm/bitnami/mysql/9.23.0

**Comment by jason-ltc** [comment]
Good job, however, it's not a bug though, since KDP requires K8s 1.26+. 
For lower K8s version, there may be incompatibility issues as reported in this issue.
