### ISSUE TITLE
[Bug]:Can you give me some help？

### ISSUE THREAD

**Issue by zmyer** [linktimecloud/kubernetes-data-platform#194]
### KDP version

KDP 1.2.2

### What did you do?

![image](https://github.com/user-attachments/assets/1b07ee83-1770-4935-be30-89b46590cd2f)
In China，there forbidden to visit outside web，is there exist some paths or image to visit?

### What did you see happen?

![image](https://github.com/user-attachments/assets/041485d2-e8b5-4bab-bc1c-6c5d625fcb62)
In China，there forbidden to visit outside web，is there exist some paths or image to visit?

### What did you expect to see?

![image](https://github.com/user-attachments/assets/d27c5c0c-4e05-497d-a3be-4438b2301cde)
In China，there exits some forbidden to visit outside web，is there exist some paths or image to visit?

**Comment by harlee-x** [comment]
Please let us know which pod is causing this exception，So that we can optimize
At present, you can pull an image on a node and identify the image by tagging it

1. `crictl/docker pull registry-cr.linktimecloud.com/busybox:1.28`
2. `crictl/docker registry-cr.linktimecloud.com/busybox:1.28 xxx busybox:1.28`

**Comment by zmyer** [comment]
Emmmmm，I have resolved it，but I found some another problem....
![image](https://github.com/user-attachments/assets/b251d14e-d4fd-442d-8bf9-0fb2f701d7ca)
Maybe it is wrong for CoreDNS，How to deal with it?

**Comment by zmyer** [comment]
> Please let us know which pod is causing this exception，So that we can optimize At present, you can pull an image on a node and identify the image by tagging it
> 
> 1. `crictl/docker pull registry-cr.linktimecloud.com/busybox:1.28`
> 2. `crictl/docker registry-cr.linktimecloud.com/busybox:1.28 xxx busybox:1.28`

Emmmmm，I have resolved it，but I found some another problem....
image
Maybe it is wrong for CoreDNS，How to deal with it?

**Comment by xingcan-ltc** [comment]
> Emmmmm，I have resolved it，but I found some another problem.... ![image](https://private-user-images.githubusercontent.com/5417297/359103082-b251d14e-d4fd-442d-8bf9-0fb2f701d7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjUxMjcsIm5iZiI6MTcyNDEyNDgyNywicGF0aCI6Ii81NDE3Mjk3LzM1OTEwMzA4Mi1iMjUxZDE0ZS1kNGZkLTQ0MmQtOGJmOS0wZmIyZjcwMWQ3Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDMzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg0Yjg3YzkxOWZjOTgyMzc1MjJjODZiMzkyYTY5ZDY1NGIzZGQwYTliNWM1Y2NiZTcwNDI5ODFjNjlkYjI1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2fhYawpeuQPL-4oejvGsOH5-8L0yiGXAX7sewc6vdrc) Maybe it is wrong for CoreDNS，How to deal with it?

1. Please check the status of the Airbyte service. Have you installed it? Is the Kubernetes service （airbyte-airbye-service-svc） reachable?
2.  Please check the Airflow logs and paste them here.

**Comment by zmyer** [comment]
> > Emmmmm，I have resolved it，but I found some another problem.... ![image](https://private-user-images.githubusercontent.com/5417297/359103082-b251d14e-d4fd-442d-8bf9-0fb2f701d7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjUxMjcsIm5iZiI6MTcyNDEyNDgyNywicGF0aCI6Ii81NDE3Mjk3LzM1OTEwMzA4Mi1iMjUxZDE0ZS1kNGZkLTQ0MmQtOGJmOS0wZmIyZjcwMWQ3Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMDMzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg0Yjg3YzkxOWZjOTgyMzc1MjJjODZiMzkyYTY5ZDY1NGIzZGQwYTliNWM1Y2NiZTcwNDI5ODFjNjlkYjI1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2fhYawpeuQPL-4oejvGsOH5-8L0yiGXAX7sewc6vdrc) Maybe it is wrong for CoreDNS，How to deal with it?
> 
> 1. Please check the status of the Airbyte service. Have you installed it? Is the Kubernetes service （airbyte-airbye-service-svc） reachable?
> 2. Please check the Airflow logs and paste them here.
1. Yes，I have
![image](https://github.com/user-attachments/assets/0d3dae09-2b4f-49f7-93af-e5dd251700d5)
2. airflow logs 
![image](https://github.com/user-attachments/assets/80485b00-8af7-4d51-b62d-9944af1f7abd)

**Comment by xingcan-ltc** [comment]
@zmyer  

1.  run `curl -v http://airbyte-airbyte-service-svc:8001` in airflow pod container, to check connectivity

**Comment by zmyer** [comment]
> 1. curl -v http://airbyte-airbyte-service-svc:8001

Emmm
![image](https://github.com/user-attachments/assets/c779af7a-9c93-407c-beac-f3d477809a7c)
