### ISSUE TITLE
kdp install failed

### ISSUE THREAD

**Issue by ninejy-io** [linktimecloud/kubernetes-data-platform#58]
root@k8s-127-master:~# ./kdp install
[INFO] - Ready to install KDP infrastructure, this may take a few minutes...
[INFO] - Ready to install vela
[INFO] - Find existing vela-core deployment, skip vela-core installation
[INFO] - Handling addon now -> [name: fluxcd] [path: /root/.kdp/src/infra/fluxcd] [parameters: (helmURL=oci://registry-cr.linktimecloud.com/linktimecloud/ registry=registry-cr.linktimecloud.com)]
[INFO] - Checking if addon fluxcd has already been installed
enabling addon by local dir: /root/.kdp/src/infra/fluxcd 
Error: Internal error occurred: failed calling webhook "validating.core.oam.dev.v1beta1.applications": failed to call webhook: Post "https://vela-core-webhook.vela-system.svc:443/validating-core-oam-dev-v1beta1-applications?timeout=10s": context deadline exceeded
[ERROR] - Error installing KDP vela addons: error installing addon fluxcd: failed to wait command: exit status 1

**Comment by jason-ltc** [comment]
@ninejy128 could you please:
- enter kind control plane container by `docker exec -it kdp-e2e-control-plane bash`
- check whether vela pods are abnormal by `kubectll get po -A`
