### ISSUE TITLE
[Feature]:Datanode binding multiple disks

### ISSUE THREAD

**Issue by stdnt-xiao** [linktimecloud/kubernetes-data-platform#72]
### Implemented function

Expect the datanode of HDFS to be able to bind multiple disks.thx
<img width="661" alt="image" src="https://github.com/linktimecloud/kubernetes-data-platform/assets/20313983/c4905de1-f38a-443a-9725-bcf433378860">

### What problem to solve?

Support adding multiple disks to solve the problem of insufficient capacity of a single disk

### What version is expected to be completed?

next

**Comment by qq157755587** [comment]
LVM can combine multiple disks into a single logical volume for use by localPV.
