### ISSUE TITLE
[Bug]:安装flink-session-cluster缺少flink-session-cluster组件依赖审核

### ISSUE THREAD

**Issue by stdnt-xiao** [linktimecloud/kubernetes-data-platform#96]
### KDP version

KDP:1.0.2

### What did you do?

安装flink-session-cluster未提示组件依赖flink-session-cluster，直接安装flink-session-cluster可以成功，但是不会创建pod。
<img width="1425" alt="image" src="https://github.com/linktimecloud/kubernetes-data-platform/assets/20313983/d04654bf-1cf6-45d5-81d8-afeeeccce3d7">

### What did you see happen?

希望安装flink-session-cluster时可以提醒安装，否则无法继续安装。

### What did you expect to see?

next

**Comment by jason-ltc** [comment]
@harlee-x We may plan the app dependency feature in some next release.
